services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  bot:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env

volumes:
  database_data:
